ifeq ($(OS),Windows_NT)
    OS_TYPE := Windows
else
    OS_TYPE := $(shell uname -s)
endif

.DEFAULT_GOAL := all
.PHONY: all package script test validate clean

all: script

package:
	@echo "--> Packaging jlox into an executable JAR..."
	./mvnw package

script: package
ifeq ($(OS_TYPE),Windows)
	@echo "--> Creating runner for Windows: jlox.cmd"
	@echo "@echo off" > jlox.cmd
	@echo "REM Autogenerated script to run jlox.jar" >> jlox.cmd
	@echo. >> jlox.cmd
	@echo "java -jar target/jlox.jar %*" >> jlox.cmd
else
	@echo "--> Creating runner for $(OS_TYPE): jlox"
	@echo "#!/bin/sh" > jlox
	@echo "# Autogenerated script to run jlox.jar" >> jlox
	@echo "" >> jlox
	@echo "java -jar target/jlox.jar \"\$$@\"" >> jlox
	@chmod +x jlox
endif
	@echo ""
	@echo "Setup complete! You can now run jlox:"
ifeq ($(OS_TYPE),Windows)
	@echo "  jlox main.lox"
else
	@echo "  ./jlox main.lox"
endif

test:
	@echo "--> Running tests..."
	./mvnw test

validate:
	@echo "--> Validating project..."
	./mvnw validate

clean:
	@echo "--> Cleaning project..."
	./mvnw clean
ifeq ($(OS_TYPE),Windows)
	@if exist jlox.cmd del jlox.cmd
	@if exist jlox del jlox
else
	@rm -f jlox jlox.cmd
endif
