name: checkstyle
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  checkstyle:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Check style
        run: ./mvnw checkstyle:check
